# Capstone - Data Visualization & Analysis
**Hazırlayan:** Zeynep Sarı

In [2]:
import pandas as pd

In [3]:
data_path = "preprocessed_data.parquet"
df = pd.read_parquet(data_path)

In [ ]:
df.head()

,age,tenure,avg_call_duration,data_usage,roaming_usage,monthly_charge,overdue_payments,auto_payment,avg_top_up_count,call_drops,...,satisfaction_score,churn,CüzdanX,HızlıPazar,Konuşalım,RitimGo,İzleGo,service_type_Broadband,service_type_Postpaid,service_type_Prepaid
id,,,,,,,,,,,,,,,,,,,,,
6549e0e5-8e85-4037-b52e-31dd3dec6624,23,45.0,14.270000,146.620000,4.700000,1761.84,0,0.499828,74,13.000000,...,5.76,0,0,0,0,0,0,0,0,1
e7091181-b875-4e74-bc34-992cd37e7dee,32,15.0,60.511764,104.610000,29.991167,366.11,1,0.000000,0,10.002964,...,7.67,0,0,0,0,0,0,1,0,0
26e3bdf7-0b20-4790-b7a8-5b626b80033a,33,16.0,31.660000,28.500000,19.750000,582.74,4,1.000000,0,20.000000,...,3.59,0,0,0,1,0,1,0,1,0
78f92350-7189-44be-8304-3ece87c88de7,19,14.0,60.511764,100.065695,29.991167,425.17,1,0.000000,0,10.002964,...,9.71,0,0,0,0,1,0,1,0,0
95aa23c8-68ec-4c33-8d10-5ed0678ff4c6,44,249.0,77.840000,100.065695,15.150000,843.20,5,0.000000,0,17.000000,...,9.34,0,0,0,0,0,0,0,1,0

In [7]:
df.churn.value_counts()/len(df)*100

churn
0    98.66347
1     1.33653
Name: count, dtype: float64